// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw9C3qXjUBCJYvGE7F1JtJ-Y-d47Ih0zY',
    appId: '1:384621015210:web:649c0e647915db7819a0d3',
    messagingSenderId: '384621015210',
    projectId: 'multiservicesapp-ec995',
    authDomain: 'multiservicesapp-ec995.firebaseapp.com',
    storageBucket: 'multiservicesapp-ec995.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq4uU-QAVd_biBJ-W5kx6XMZW4acxO0G8',
    appId: '1:384621015210:android:e27bd362e47761d019a0d3',
    messagingSenderId: '384621015210',
    projectId: 'multiservicesapp-ec995',
    storageBucket: 'multiservicesapp-ec995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCNVFt-ygbf7Q9WrOcSn7PzjEkLg95a_g',
    appId: '1:384621015210:ios:f4b2d110dd2ac86f19a0d3',
    messagingSenderId: '384621015210',
    projectId: 'multiservicesapp-ec995',
    storageBucket: 'multiservicesapp-ec995.firebasestorage.app',
    androidClientId: '384621015210-k3vlkr8rnk5pi7q2o8piomrdtogj7fie.apps.googleusercontent.com',
    iosClientId: '384621015210-lqph6gejcigoob71fkreuscql9nk1ap7.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiservicesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCNVFt-ygbf7Q9WrOcSn7PzjEkLg95a_g',
    appId: '1:384621015210:ios:f4b2d110dd2ac86f19a0d3',
    messagingSenderId: '384621015210',
    projectId: 'multiservicesapp-ec995',
    storageBucket: 'multiservicesapp-ec995.firebasestorage.app',
    androidClientId: '384621015210-k3vlkr8rnk5pi7q2o8piomrdtogj7fie.apps.googleusercontent.com',
    iosClientId: '384621015210-lqph6gejcigoob71fkreuscql9nk1ap7.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiservicesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw9C3qXjUBCJYvGE7F1JtJ-Y-d47Ih0zY',
    appId: '1:384621015210:web:793880ddff7cb51f19a0d3',
    messagingSenderId: '384621015210',
    projectId: 'multiservicesapp-ec995',
    authDomain: 'multiservicesapp-ec995.firebaseapp.com',
    storageBucket: 'multiservicesapp-ec995.firebasestorage.app',
  );

}